import { execSync } from 'node:child_process';
import { parseWranglerConfig } from './utils/parse-wrangler.mjs';
import { createId } from '@paralleldrive/cuid2';

const coaches = [
  { name: "Abi Williams", credentials: "Owner, CrossFit L1", bio: 'Meet Coach Abi Williams!\nAbi grew up in Emmett, ID and graduated from Emmett High School before heading to trade school to become a Dental Assistant. After 9 years in the dental field, she made the bold move to follow her true passion—pursuing Nutrition Coaching and working full-time at CrossFit Canvas!\n\nAbi\'s own fitness journey started back in 2015. Wanting to feel stronger and healthier, she began training at a traditional gym. Her first big challenge? Training for Spartan Races! After years of strength training and obstacle race prep, she discovered CrossFit in 2018—and she\'s been hooked ever since.\n\nFavorite thing about coaching CrossFit?\n"Helping people realize they\'re capable of way more than they ever thought possible—and watching them crush goals inside and outside the gym."\n\nGoals for the future?\n"To continue growing our CrossFit Canvas community, expand my reach as a Nutrition Coach, and keep helping people live stronger, healthier lives."' },
  { name: "Jon Williams", credentials: "Owner, CrossFit L2", bio: "Meet Coach Jon Williams!\nJon grew up in Emmett, ID and graduated from Vallivue High School before taking his basketball talents to the college level. He played at TVCC in Ontario, Oregon where he earned an Associate's Degree in Physical Education, then transferred to Grandview University in Des Moines, Iowa. There, he played another two years of college basketball while interning with the athletic department's strength & conditioning team during his senior year —graduating in 2016 with a Bachelor's in Kinesiology & Health Promotion.\n\nAfter college, Jon jumped straight into personal training & coaching CrossFit and never looked back. Two years later, in 2019, he and his wife Abi opened the doors to CrossFit Canvas!\n\nJon is going into his 9th year coaching and has his CrossFit Level 2 certification!\n\nFavorite thing about coaching CrossFit?\n\"Watching people do things they never thought they could. Seeing confidence and strength grow inside and outside the gym for our members means so much to us. There have been so many people come through the doors at CrossFit Canvas and to know we hopefully had a positive impact on their lives is why we love doing what we do.\"\n\nGoals for the future?\n\"To keep building a strong, encouraging community at CrossFit Canvas that helps push each other to be better every day—both fitness wise and as people. We don't know how long we're here for or how long we'll be doing this before life changes so we hope to make as much impactful change as possible.\"" },
  { name: "Andrea Goff", credentials: "CrossFit L1", bio: "I grew up in Caldwell, Idaho, and spent my childhood summers in South Texas, where I was born. I've been married to my husband, Ryan, for 23 years this June, and we have two awesome kiddos, Cash and Presley.\n\nI graduated from Vallivue High School and went on to attend Boise State University.\n\nI enjoy remodeling & home decorating projects in my \"spare\" time. Over the years, I have learned how to build things, knock down walls, remove cabinets hang shiplap, etc. I love it!!\n\nMy family and I are extremely active — you'll find us wakesurfing, hiking & enjoying our pool in the summer, and we love to travel. We're big fans of all things fitness and spend a lot of time cheering on our kids at their sporting events. It's truly the BEST!\n\nI've been a CrossFit coach for six years. When I'm not coaching, I run my own retail and custom t-shirt business, G4 Collective.\n\nWhat I love most about coaching is getting to be a part of someone's day for an hour & making those connections. It's an honor to show up, encourage them, and hopefully leave them feeling stronger and happier than when they walked in.\n\nLooking ahead, I'm currently working toward my CrossFit Level 2 certification. I'm also passionate about furthering my education in women's health/fitness — especially for women 40 and over. It's so important for women in this stage of life to continue building and maintaining muscle through weight training and nutrition." },
  { name: "Dre Lucich", credentials: "CrossFit L2", bio: "Where did you grow up?\nSunny San Diego, California\n\nEducation:\nI swam for Boise State University from 2007-2011 while earning my Bachelor's in Elementary Education.\n\nSports, Hobbies & Activities:\nCrossFit (surprise!), dance parties with my daughter Kennedy, coaching Meridian High School's Swim Team, drinking way too much coffee, crafting, being outdoors, and doing anything in the water!\n\nCareer:\nI spent 7 amazing years teaching elementary school before transitioning to my most rewarding role yet-stay-at-home mom to Kennedy.\n\nFavorite Thing About Coaching CrossFit:\nWatching people build confidence not just in the gym, but in life. I love connecting with each athlete and being a part of their journey-especially as they kick butt into their 90s!\n\nGoals:\nPersonal Goal: Improve my gymnastics and hit a 350 lb deadlift\nCoaching Goal: Earn my Pregnancy & Postpartum Athleticism certification and eventually test for the Level 3 (L3) Coaching Credential" },
  { name: "JT Hand", credentials: "CrossFit L2", bio: "JT spent his early childhood in California before moving to Meridian, Idaho in the early '90s. He graduated from Centennial High School, where he played baseball, eventually going on to play for the Detroit Tigers' long A team right out of high school.\n\nAfter returning from baseball, JT met his wife Jamie. They've been married for over 25 years and have two children-Trevor and Tia.\n\nJT has been coaching CrossFit for over 15 years and is passionate about connecting with people and helping them reach their fitness goals. He loves seeing members progress and grow on their fitness journeys.\n\nWhen he's not coaching, JT is focused on his own health and fitness-especially when it involves mountain biking anywhere and everywhere he can.\n\nCrossFit Canvas has been very lucky to have JT on the team for the entire almost 6 years now that we have been open!! You can catch JT coaching some class at almost all times, and you'll rarely catch him without a smile on his face and a backwards hat on!!" },
  { name: "JT Mahon", credentials: "CrossFit L2", bio: "Born and raised in Council, Idaho, JT grew up logging with his dad or dominating the field-earning All-State honors in football, basketball, and track. He went on to compete in football and track at both the University of Idaho and The College of Idaho, where he earned his undergraduate degree.\n\nCurrently, he's a Bronco working toward his MBA while leading the night shift at the Amazon Fulfillment Center near the Idaho Center.\n\nOutside the gym, he's either watching football or deep in a DIY home project-\"DIY for life!\"\n\nAs a coach, JT finds the most reward in seeing people grow, change, and develop through hard work and determination.\n\n\"My personal goal is to maintain an able body-to be a competitor and a protector. As a coach, I want to help people stay focused on their own journey. Comparison is the thief of joy!\"" },
  { name: "Liz Krmpotich", credentials: "CrossFit L2", bio: "Born and raised in Green River, Wyoming, Liz has been breaking barriers from the start-literally! She was one of the first female athletes in the state to compete in pole vaulting and also made waves as a competitive diver. She even turned down a scholarship to dive at UNLV to marry her high school sweetheart, Bobby, and begin their adventure together.\n\nNow living in Idaho, Liz wears many hats: mom to Cole and Lexi, licensed property appraiser, office manager of Balanced Electric (which she co-owns with Bobby), and of course, CrossFit coach extraordinaire!\n\nHer passion for movement and adventure knows no bounds-she's run multiple half marathons, hiked across Europe, swam in the Adriatic and Baltic Seas, and even backpacked the Na Pali Coast. Paddleboarding, cliff diving, and CrossFit? She's all in.\n\nLiz found CrossFit in 2012 and began coaching in 2015. Helping others discover their strength-both inside and out-is the highlight of her day.\n\nHer bucket list?\nHike the Appalachian Trail\nCompete on Survivor\nDo CrossFit until she's 100" },
  { name: "Tyler Berkheiser", credentials: "CrossFit L1", bio: "Hometown Roots: Tyler grew up in Meridian, Idaho, and has also lived in Salt Lake City, St. George, San Antonio, and Biloxi.\n\nEducation: A proud Meridian High School grad and Idaho State University alum.\n\nAthletic Background: Tyler brings years of athleticism to the floor - from sprinting on the track (100m, long jump, 4x100m relay) to powering through as a football running back and wide receiver.\n\nWhy He Coaches: \"Helping others reach their goals - whether it's their first pull-up, losing 10 lbs, or stepping into their first competition - that's what lights me up.\"\n\nWhat's Next: Tyler's dedicated to continuing his education and finding new ways to serve and inspire the CrossFit community." },
  { name: "Zac Jones", credentials: "CrossFit L2", bio: "I started CrossFit back in 2013 and immediately fell in love with the constant challenge and variety that it gave my workout routine every day. The community that is built around suffering together is a highlight as well.\n\nAs I've learned the CrossFit methodology and refined my movement I really enjoy supporting others fitness journeys and teaching people what I've learned. I'm always happy to talk about methodology, nutrition, weightlifting or anything fitness related." },
  { name: "Katirah Vangaasbeck", credentials: "CrossFit L1", bio: "I started CrossFit in December 2021, and it quickly became my favorite part of the day. I love how it pushes you out of your comfort zone in the best way both mentally and physically.\n\nOutside of the gym, I love hanging out with my dogs, fostering animals, thrifting, and traveling.\n\nI'm all about creating a space where people feel safe to mess up, try again, laugh, grow, and do things that might scare them. I want everyone to feel welcome, supported, and capable." },
];

function generateSlug(name) {
  return name.toLowerCase().replace(/[^a-z0-9\s-]/g, '').replace(/\s+/g, '-').replace(/-+/g, '-').trim();
}

function escSql(str) {
  return str.replace(/'/g, "''");
}

const isRemote = process.argv.includes('--remote');
const config = parseWranglerConfig();
const dbName = config.d1_databases?.find(db => db.binding === 'DB')?.database_name;

if (!dbName) {
  console.error('Database name not found in wrangler.jsonc');
  process.exit(1);
}

const now = Math.floor(Date.now() / 1000);

const statements = coaches.map((coach) => {
  const id = `coach_${createId()}`;
  const slug = generateSlug(coach.name);
  return `INSERT OR IGNORE INTO coach (id, name, slug, credentials, bio, createdAt, updatedAt) VALUES ('${escSql(id)}', '${escSql(coach.name)}', '${escSql(slug)}', '${escSql(coach.credentials)}', '${escSql(coach.bio)}', ${now}, ${now});`;
});

const sql = statements.join('\n');

const flag = isRemote ? '--remote' : '--local';

console.log(`Seeding ${coaches.length} coaches (${isRemote ? 'PRODUCTION' : 'local'})...\n`);

try {
  execSync(`wrangler d1 execute ${dbName} ${flag} --command "${sql.replace(/"/g, '\\"')}"`, {
    stdio: 'inherit',
    cwd: process.cwd(),
  });
  console.log(`\nSeeded ${coaches.length} coaches successfully.`);
} catch (error) {
  console.error('Failed to seed coaches:', error.message);
  process.exit(1);
}
